import Head from 'next/head'
import { useRouter } from 'next/router';
import { TweetLine } from '../components/twpost';

const UserPage = () => {
  const router = useRouter();
  const name = router.query.name as string;
  return (
    <>
      <Head>
        <title>Home / Twitter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>d</h1>
        <TweetLine where={ {author:{
          name
        }}}/>
      </div>
    </> 
  );
};
export default UserPage
