import React, { useState } from 'react'
import Head from 'next/head'
import { trpc } from '../utils/trpc';
import { S3 } from "aws-sdk";

const images = () => {

  const [file, setFile] = useState<any>(null);

  const  { mutateAsync: createPresignedUrl } = trpc.tweet.createPresignedUrl.useMutation();
  
  const { data: images, refetch: refetchImages } = trpc.tweet.getImagesForUser.useQuery();

  const onFileChange = (e: React.FormEvent<HTMLInputElement>) => {
    setFile(e.currentTarget.files?.[0]);
  }
  const uploadImage = async (e: React.FormEvent<HTMLInputElement>) => {
    e.preventDefault();
    if (!file) return;

    const { url, fields }: { url: string, fields: any } = await createPresignedUrl() as any;
    const data = { ...fields, 'Content-type': file.type, file }
    const formData = new FormData();
    for (const name in data) {
      formData.append(name, data[name]);
    }

    await fetch(url,{
      method: 'POST',
      body: formData,
    })
    console.log("dsadasd");
    refetchImages();
  }
  // console.log(images);
  return (
    <>
      <Head>
        <title>UPload Images</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center pt-64 pb-64 mx-auto h-full w-[1000px]'>
        <h1 className='text-4xl mb-4'>
          Images
        </h1>
        <form onSubmit={uploadImage}>
          Upload New Image
          <input onChange={onFileChange} type="file" accept='image/*, video/*'></input>
          <button type='submit'>Upload</button>
        </form>
        <div className='grid grid-cols-4'>
          {images && images.map(image => (
            <div key={image.id} className='col-span-4'>
              <img src={image.url} alt="alt" />
            </div>
          ))}

        </div>
      </div>
    </>
  )
}

export default images